//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:32:30 AM EDT 
//


package net.maurerit.mtg.deck;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import mage.tracker.domain.Card;
import mage.tracker.domain.CardEdition;


/**
 * TODO: Document Me.
 * 
 * <p>Java class for Deck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deck">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mainBoardCard" type="{http://xml.model.magefree.com}Card" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sideBoardCard" type="{http://xml.model.magefree.com}Card" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="finished" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Table(uniqueConstraints = {

}, name = "DECK")
public class Deck
    implements Serializable
{
    @ManyToMany(cascade = {

    })
    @JoinTable(inverseJoinColumns = {

    }, uniqueConstraints = {

    }, name = "DECK_MAINBOARDCARDS", joinColumns = {

    })
    protected List<CardEdition> mainBoardCards;
    @ManyToMany(cascade = {

    })
    @JoinTable(inverseJoinColumns = {

    }, uniqueConstraints = {

    }, name = "DECK_SIDEBOARDCARDS", joinColumns = {

    })
    protected List<CardEdition> sideBoardCards;
    protected String name;
    protected String author;
    protected String format;
    protected String location;
    protected String finished;
    protected Calendar date;
    @Id
    protected String id;

    /**
     * Gets the value of the mainBoardCards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mainBoardCards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMainBoardCards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardEdition }
     * 
     * 
     */
    public List<CardEdition> getMainBoardCards() {
        if (mainBoardCards == null) {
            mainBoardCards = new ArrayList<CardEdition>();
        }
        return this.mainBoardCards;
    }

    /**
     * Gets the value of the sideBoardCards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sideBoardCards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSideBoardCards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardEdition }
     * 
     * 
     */
    public List<CardEdition> getSideBoardCards() {
        if (sideBoardCards == null) {
            sideBoardCards = new ArrayList<CardEdition>();
        }
        return this.sideBoardCards;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the finished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinished() {
        return finished;
    }

    /**
     * Sets the value of the finished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinished(String value) {
        this.finished = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(Calendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public void setMainBoardCards(List<CardEdition> value) {
        this.mainBoardCards = value;
    }

    public void setSideBoardCards(List<CardEdition> value) {
        this.sideBoardCards = value;
    }

}
